### ISSUE TITLE
Simple *.conf file loading/configuration?

### ISSUE THREAD

**Issue by cluelessperson** [linuxserver/docker-openvpn-as#100]
I don't want to use the AS setup?

**Comment by j0nnymoe** [comment]
What?

**Comment by cluelessperson** [comment]
It seems this configuration is built around using a gui to configure
openvpn.

Is there a simple method to load simple server.conf files from the comfort
directory to host a VPN server?

**Comment by j0nnymoe** [comment]
No not with this image. This image is built using OpenVPN's Access Server.
