### ISSUE TITLE
Fails to configure service

### ISSUE THREAD

**Issue by lorenalexm** [linuxserver/docker-openvpn-as#104]
## Expected Behavior
When creating a new container from the linuxserver/openvpn-as:latest the container should start and configure itself correctly.

## Current Behavior
The configuration of the container fails as _systemctl_ cannot be found, preventing the service from running.

## Steps to Reproduce

1. Pull linuxserver/openvpn-as:latest
2. Create a new container using the image
3. openvpn-as service fails as container cannot find _systemctl_

## Environment
**OS:**      Ubuntu 18.04.3 LTS as an ESXi 6.5 VM
**CPU architecture:** x86_64      
**How docker service was installed:**      https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04

## Command used to create docker container (run/create/compose/screenshot)

![portainer_openvpn_as](https://user-images.githubusercontent.com/6470175/75168670-231b3180-56dc-11ea-8f30-2ebce8c25c46.jpg)
_GUID_ was changed to the expected _PGID_ after the screenshot was taken, no change in issue.

## Docker logs

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
> [s6-init] ensuring user provided files have correct perms...exited 0.,
> [fix-attrs.d] applying ownership & permissions fixes...,
> [fix-attrs.d] done.,
> [cont-init.d] executing container initialization scripts...,
> [cont-init.d] 01-envfile: executing... ,
> [cont-init.d] 01-envfile: exited 0.,
> [cont-init.d] 10-adduser: executing... ,
> ,
> -------------------------------------,
>           _         (),
>          | |  ___   _    __,
>          | | / __| | |  /  \ ,
>          | | \__ \ | | | () |,
>          |_| |___/ |_|  \__/,
> ,
> ,
> Brought to you by linuxserver.io,
> We gratefully accept donations at:,
> https://www.linuxserver.io/donate/,
> -------------------------------------,
> GID/UID,
> -------------------------------------,
> ,
> User uid:    1000,
> User gid:    911,
> -------------------------------------,
> ,
> [cont-init.d] 10-adduser: exited 0.,
> [cont-init.d] 20-time: executing... ,
> ,
> Current default time zone: 'Etc/UTC',
> Local time is now:      Mon Feb 24 15:44:59 UTC 2020.,
> Universal Time is now:  Mon Feb 24 15:44:59 UTC 2020.,
> ,
> [cont-init.d] 20-time: exited 0.,
> [cont-init.d] 30-config: executing... ,
> existing data found, reinstalling openvpn-as,
> backing up certs.db,
> backing up cluster.db,
> backing up config.db,
> backing up config_local.db,
> backing up log.db,
> backing up notification.db,
> backing up userprop.db,
> backing up as.conf,
> Selecting previously unselected package openvpn-as-bundled-clients.,
> (Reading database ... 13024 files and directories currently installed.),
> Preparing to unpack /openvpn/openvpn-clients.deb ...,
> Unpacking openvpn-as-bundled-clients (5) ...,
> Setting up openvpn-as-bundled-clients (5) ...,
> Selecting previously unselected package openvpn-as.,
> (Reading database ... 13037 files and directories currently installed.),
> Preparing to unpack /openvpn/openvpn.deb ...,
> Unpacking openvpn-as (2.8.1-3ae74700-Ubuntu18) ...,
> Setting up openvpn-as (2.8.1-3ae74700-Ubuntu18) ...,
> Automatic configuration failed, see /usr/local/openvpn_as/init.log,
> You can configure manually using the /usr/local/openvpn_as/bin/ovpn-init tool.,
> /var/lib/dpkg/info/openvpn-as.postinst: line 72: systemctl: command not found,
> Stopping openvpn-as now; will start again later after configuring,
> cat: /var/run/openvpnas.pid: No such file or directory,
> kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec],
> restoring certs.db,
> restoring cluster.db,
> restoring config.db,
> restoring config_local.db,
> restoring log.db,
> restoring notification.db,
> restoring userprop.db,
> restoring as.conf,
> [cont-init.d] 30-config: exited 0.,
> [cont-init.d] 40-openvpn-init: executing... ,
> [cont-init.d] 40-openvpn-init: exited 0.,
> [cont-init.d] 50-interface: executing... ,
> MOD Default {} {},
> MOD Default {} {},
> MOD Default {} {},
> MOD Default {} {},
> [cont-init.d] 50-interface: exited 0.,
> [cont-init.d] 99-custom-scripts: executing... ,
> [custom-init] no custom files found exiting...,
> [cont-init.d] 99-custom-scripts: exited 0.,
> [cont-init.d] done.,
> [services.d] starting services,
> [services.d] done.,

**Comment by aptalca** [comment]
That's a harmless error. We use s6 as the supervisor, not systemd. Openvpn tries to auto-start itself via systemd and fails. We start it later via s6 and configure it correctly:
```
[services.d] starting services,
[services.d] done.,
```

**Comment by lorenalexm** [comment]
Firstly, thank you for the prompt reply, it is greatly appreciated. I guess I had become so hung-up on the _systemctl_ message that I failed to look further through the logs; coupled with a routing error on my part preventing me from being able to gain access to the service. Thank you again!

**Comment by aptalca** [comment]
No worries. In the previous version of openvpn, it would fall back on other methods of auto starting itself, which messed up our init process. So we had to get aggressive and add other methods to kill it as we don't want it running until after all init steps are completed. So you see some other errors in the log related to them but it all works out at the end.
