### ISSUE TITLE
ARM Build

### ISSUE THREAD

**Issue by mpeirone** [linuxserver/docker-openvpn-as#119]
Hi, thanks for your great work.

Why this image isn't build for ARM?

I tried to build this image on ARM device and it works.

Thanks

Matteo

**Comment by aptalca** [comment]
Can you share a build log?
and a container log?
Afaik, openvpn does not publish binaries for arm

**Comment by mpeirone** [comment]
Sorry for this question.

I tried but it doesn't work, it compiles but can't find the package.

Thanks anyway.

**Comment by mzramna** [comment]
it is possible to build openvpn to arm:
https://github.com/OpenVPN/openvpn-build/issues/31
since this it is possible to create an arm variation of the container using build instead of apt install?

**Comment by aptalca** [comment]
`openvpn` and `openvpn-as` are two different things
