### ISSUE TITLE
How to use in China?

### ISSUE THREAD

**Issue by hbqclh** [linuxserver/docker-openvpn-as#123]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## I am from magical China. Many sites can not be accessed here.

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      

## Command used to create docker container (run/create/compose/screenshot)

![image](https://user-images.githubusercontent.com/12690057/84745694-86143980-afe7-11ea-84f0-b944c7ea86a8.png)

I try to use a proxy, but failed.
![image](https://user-images.githubusercontent.com/12690057/84745736-962c1900-afe7-11ea-9f11-5e07eb8de50f.png)

**Comment by aptalca** [comment]
Sorry, if you cannot connect to the openvpn-as repo, this image won't work and I don't have a solution for you.
