### ISSUE TITLE
Admin Portal Not Opening

### ISSUE THREAD

**Issue by capriciousduck** [linuxserver/docker-openvpn-as#125]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
The admin portal should open

## Current Behavior
When I visit the IP of my DO droplet, I don't see the admin portal. And all the ports of my droplet are open.
## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      

## Command used to create docker container (run/create/compose/screenshot)
`docker run -d --name=openvpn \
--restart=always \
-v openvpn_config:/config \
-e INTERFACE=eth0 \
-e PGID=0 -e PUID=0 \
-e TZ=Europe/Helsinki \
--net=host --privileged \
linuxserver/openvpn-as`
## Docker logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    0
User gid:    0
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-time: executing... 

Current default time zone: 'Asia/Kolkata'
Local time is now:      Tue Jun 23 17:54:44 IST 2020.
Universal Time is now:  Tue Jun 23 12:24:44 UTC 2020.

[cont-init.d] 20-time: exited 0.
[cont-init.d] 30-config: executing... 
existing data found, reinstalling openvpn-as
backing up certs.db
backing up cluster.db
backing up config.db
backing up config_local.db
backing up log.db
backing up notification.db
backing up userprop.db
backing up as.conf
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://as-repository.openvpn.net/as/debian bionic InRelease [3,185 B]
Get:4 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:5 http://as-repository.openvpn.net/as/debian bionic/main amd64 Packages [3,542 B]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/universe Sources [373 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/main Sources [411 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1,253 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,397 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic-security/main Sources [198 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [961 kB]
Fetched 4,777 kB in 1s (3,359 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  openvpn-as-bundled-clients
The following NEW packages will be installed:
  openvpn-as openvpn-as-bundled-clients
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 151 MB of archives.
After this operation, 202 MB of additional disk space will be used.
Get:1 http://as-repository.openvpn.net/as/debian bionic/main amd64 openvpn-as-bundled-clients all 11 [130 MB]
Get:2 http://as-repository.openvpn.net/as/debian bionic/main amd64 openvpn-as amd64 2.8.4-39c4563c-Ubuntu18 [21.1 MB]
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 2.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 2.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 151 MB in 3s (47.3 MB/s)
Selecting previously unselected package openvpn-as-bundled-clients.
(Reading database ... 13212 files and directories currently installed.)
Preparing to unpack .../openvpn-as-bundled-clients_11_all.deb ...
Unpacking openvpn-as-bundled-clients (11) ...
Selecting previously unselected package openvpn-as.
Preparing to unpack .../openvpn-as_2.8.4-39c4563c-Ubuntu18_amd64.deb ...
Unpacking openvpn-as (2.8.4-39c4563c-Ubuntu18) ...
Setting up openvpn-as-bundled-clients (11) ...
Setting up openvpn-as (2.8.4-39c4563c-Ubuntu18) ...
Automatic configuration failed, see /usr/local/openvpn_as/init.log
You can configure manually using the /usr/local/openvpn_as/bin/ovpn-init tool.
/var/lib/dpkg/info/openvpn-as.postinst: line 68: systemctl: command not found
Stopping openvpn-as now; will start again later after configuring
cat: /var/run/openvpnas.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
restoring certs.db
restoring cluster.db
restoring config.db
restoring config_local.db
restoring log.db
restoring notification.db
restoring userprop.db
restoring as.conf
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-openvpn-init: executing... 
[cont-init.d] 40-openvpn-init: exited 0.
[cont-init.d] 50-interface: executing... 
MOD Default {} {}
MOD Default {} {}
MOD Default {} {}
MOD Default {} {}
[cont-init.d] 50-interface: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by aptalca** [comment]
Use the parameters we suggest in the readme, like bridge networking

**Comment by capriciousduck** [comment]
I did try bridge networking, the result is the same. In fact, I used the same command(without interface env), the first time, which is in the readme.

**Comment by capriciousduck** [comment]
Tried today after the latest update, still admin portal not opening. I see the following lines in the log and I guess that this is why the portal doesn't open.

`Error: Could not execute 'systemctl enable openvpnas' to enable startup/shutdown scripts
Stopping openvpn-as now; will start again later after configuring
cat: /var/run/openvpnas.pid: No such file or directory`

Full log:

`root@zeus:~# docker run \
>   --name=openvpn \
>   --cap-add=NET_ADMIN \
>  --privileged \
>   -e TZ=Europe/Helsinki \
>   -p 943:943 \
>   -p 9443:9443 \
>   -p 1194:1194/udp \
>   -v openvpn_config:/config \
>   --restart unless-stopped \
>   linuxserver/openvpn-as
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-time: executing... 

Current default time zone: 'Europe/Helsinki'
Local time is now:      Wed Jun 24 19:40:26 EEST 2020.
Universal Time is now:  Wed Jun 24 16:40:26 UTC 2020.

[cont-init.d] 20-time: exited 0.
[cont-init.d] 30-config: executing... 
mknod: /dev/net/tun: Operation not permitted
installing openvpn-as for the first time
Get:1 http://as-repository.openvpn.net/as/debian bionic InRelease [3,185 B]
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://as-repository.openvpn.net/as/debian bionic/main amd64 Packages [3,542 B]
Get:5 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main Sources [411 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/universe Sources [372 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,397 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1,254 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic-security/main Sources [198 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [961 kB]
Fetched 4,777 kB in 2s (2,132 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  openvpn-as-bundled-clients
The following NEW packages will be installed:
  openvpn-as openvpn-as-bundled-clients
0 upgraded, 2 newly installed, 0 to remove and 2 not upgraded.
Need to get 151 MB of archives.
After this operation, 202 MB of additional disk space will be used.
Get:1 http://as-repository.openvpn.net/as/debian bionic/main amd64 openvpn-as-bundled-clients all 11 [130 MB]
Get:2 http://as-repository.openvpn.net/as/debian bionic/main amd64 openvpn-as amd64 2.8.4-39c4563c-Ubuntu18 [21.1 MB]
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 2.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 2.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 151 MB in 3s (47.1 MB/s)
Selecting previously unselected package openvpn-as-bundled-clients.
(Reading database ... 13212 files and directories currently installed.)
Preparing to unpack .../openvpn-as-bundled-clients_11_all.deb ...
Unpacking openvpn-as-bundled-clients (11) ...
Selecting previously unselected package openvpn-as.
Preparing to unpack .../openvpn-as_2.8.4-39c4563c-Ubuntu18_amd64.deb ...
Unpacking openvpn-as (2.8.4-39c4563c-Ubuntu18) ...
Setting up openvpn-as-bundled-clients (11) ...
Setting up openvpn-as (2.8.4-39c4563c-Ubuntu18) ...
Automatic configuration failed, see /usr/local/openvpn_as/init.log
You can configure manually using the /usr/local/openvpn_as/bin/ovpn-init tool.
/var/lib/dpkg/info/openvpn-as.postinst: line 68: systemctl: command not found
Stopping openvpn-as now; will start again later after configuring
cat: /var/run/openvpnas.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-openvpn-init: executing... 
Detected an existing OpenVPN-AS configuration.
Continuing will delete this configuration and restart from scratch.
Please enter 'DELETE' to delete existing configuration: 
          OpenVPN Access Server
          Initial Configuration Tool
------------------------------------------------------
OpenVPN Access Server End User License Agreement (OpenVPN-AS EULA)

    1. Copyright Notice: OpenVPN Access Server License;
       Copyright (c) 2009-2020 OpenVPN Inc. All rights reserved.
       "OpenVPN" is a trademark of OpenVPN Inc.
    2. Redistribution of OpenVPN Access Server binary forms and related documents,
       are permitted provided that redistributions of OpenVPN Access Server binary
       forms and related documents reproduce the above copyright notice as well as
       a complete copy of this EULA.
    3. You agree not to reverse engineer, decompile, disassemble, modify,
       translate, make any attempt to discover the source code of this software,
       or create derivative works from this software.
    4. The OpenVPN Access Server is bundled with other open source software
       components, some of which fall under different licenses. By using OpenVPN
       or any of the bundled components, you agree to be bound by the conditions
       of the license for each respective component. For more information, you can
       find our complete EULA (End-User License Agreement) on our website
       (http://openvpn.net), and a copy of the EULA is also distributed with the
       Access Server in the file /usr/local/openvpn_as/license.txt.
    5. This software is provided "as is" and any expressed or implied warranties,
       including, but not limited to, the implied warranties of merchantability
       and fitness for a particular purpose are disclaimed. In no event shall
       OpenVPN Inc. be liable for any direct, indirect, incidental,
       special, exemplary, or consequential damages (including, but not limited
       to, procurement of substitute goods or services; loss of use, data, or
       profits; or business interruption) however caused and on any theory of
       liability, whether in contract, strict liability, or tort (including
       negligence or otherwise) arising in any way out of the use of this
       software, even if advised of the possibility of such damage.
    6. OpenVPN Inc. is the sole distributor of OpenVPN Access Server
       licenses. This agreement and licenses granted by it may not be assigned,
       sublicensed, or otherwise transferred by licensee without prior written
       consent of OpenVPN Inc. Any licenses violating this provision
       will be subject to revocation and deactivation, and will not be eligible
       for refunds.
    7. A purchased license entitles you to use this software for the duration of
       time denoted on your license key on any one (1) particular device, up to
       the concurrent user limit specified by your license. Multiple license keys
       may be activated to achieve a desired concurrency limit on this given
       device. Unless otherwise prearranged with OpenVPN Inc.,
       concurrency counts on license keys are not to be divided for use amongst
       multiple devices. Upon activation of the first purchased license key in
       this software, you agree to forego any free licenses or keys that were
       given to you for demonstration purposes, and as such, the free licenses
       will not appear after the activation of a purchased key. You are
       responsible for the timely activation of these licenses on your desired
       server of choice. Refunds on purchased license keys are only possible
       within 30 days of purchase of license key, and then only if the license key
       has not already been activated on a system. To request a refund, contact us
       through our support ticket system using the account you have used to
       purchase the license key. Exceptions to this policy may be given for
       machines under failover mode, and when the feature is used as directed in
       the OpenVPN Access Server user manual. In these circumstances, a user is
       granted one (1) license key (per original license key) for use solely on
       failover purposes free of charge. Other failover and/or load balancing use
       cases will not be eligible for this exception, and a separate license key
       would have to be acquired to satisfy the licensing requirements. To request
       a license exception, please file a support ticket in the OpenVPN Access
       Server ticketing system. A staff member will be responsible for determining
       exception eligibility, and we reserve the right to decline any requests not
       meeting our eligibility criteria, or requests which we believe may be
       fraudulent in nature.
    8. Activating a license key ties it to the specific hardware/software
       combination that it was activated on, and activated license keys are
       nontransferable. Substantial software and/or hardware changes may
       invalidate an activated license. In case of substantial software and/or
       hardware changes, caused by for example, but not limited to failure and
       subsequent repair or alterations of (virtualized) hardware/software, our
       software product will automatically attempt to contact our online licensing
       systems to renegotiate the licensing state. On any given license key, you
       are limited to three (3) automatic renegotiations within the license key
       lifetime. After these renegotiations are exhausted, the license key is
       considered invalid, and the activation state will be locked to the last
       valid system configuration it was activated on. OpenVPN Inc.reserves the
       right to grant exceptions to this policy for license holders under
       extenuating circumstances, and such exceptions can be requested through a
       ticket via the OpenVPN Access Server ticketing system.
    9. Once an activated license key expires or becomes invalid, the concurrency
       limit on our software product will decrease by the amount of concurrent
       connections previously granted by the license key. If all of your purchased
       license key(s) have expired, the product will revert to demonstration mode,
       which allows a maximum of two (2) concurrent users to be connected to your
       server. Prior to your license expiration date(s), OpenVPN Inc. will attempt
       to remind you to renew your license(s) by sending periodic email messages
       to the licensee email address on record. You are solely responsible for
       the timely renewal of your license key(s) prior to their expiration if
       continued operation is expected after the license expiration date(s).
       OpenVPN Inc. will not be responsible for any misdirected and/or undeliverable
       email messages, nor does it have an obligation to contact you regarding
       your expiring license keys.
   10. Any valid license key holder is entitled to use our ticketing system for
       support questions or issues specifically related to the OpenVPN Access
       Server product. To file a ticket, go to our website at http://openvpn.net/
       and sign in using the account that was registered and used to purchase the
       license key(s). You can then access the support ticket system through our
       website and submit a support ticket. Tickets filed in the ticketing system
       are answered on a best-effort basis. OpenVPN Inc. staff
       reserve the right to limit responses to users of our demo / expired
       licenses, as well as requests that substantively deviate from the OpenVPN
       Access Server product line. Tickets related to the open source version of
       OpenVPN will not be handled here.
   11. Purchasing a license key does not entitle you to any special rights or
       privileges, except the ones explicitly outlined in this user agreement.
       Unless otherwise arranged prior to your purchase with OpenVPN,
       Inc., software maintenance costs and terms are subject to change after your
       initial purchase without notice. In case of price decreases or special
       promotions, OpenVPN Inc. will not retrospectively apply
       credits or price adjustments toward any licenses that have already been
       issued. Furthermore, no discounts will be given for license maintenance
       renewals unless this is specified in your contract with OpenVPN Inc.

Please enter 'yes' to indicate your agreement [no]: 
Once you provide a few initial configuration settings,
OpenVPN Access Server can be configured by accessing
its Admin Web UI using your Web browser.

Will this be the primary Access Server node?
(enter 'no' to configure as a backup or standby node)
> Press ENTER for default [yes]: 
Please specify the network interface and IP address to be
used by the Admin Web UI:
(1) all interfaces: 0.0.0.0
(2) eth0: 172.17.0.7
Please enter the option number from the list above (1-2).
> Press Enter for default [1]: 
Please specify the port number for the Admin Web UI.
> Press ENTER for default [943]: 
Please specify the TCP port number for the OpenVPN Daemon
> Press ENTER for default [443]: 
Should client traffic be routed by default through the VPN?
> Press ENTER for default [yes]: 
Should client DNS traffic be routed by default through the VPN?
> Press ENTER for default [yes]: 
Use local authentication via internal DB?
> Press ENTER for default [yes]: 
Private subnets detected: ['172.17.0.0/16']

Should private subnets be accessible to clients by default?
> Press ENTER for default [yes]: 
To initially login to the Admin Web UI, you must use a
username and password that successfully authenticates you
with the host UNIX system (you can later modify the settings
so that RADIUS or LDAP is used for authentication instead).

You can login to the Admin Web UI as "openvpn" or specify
a different user account to use for this purpose.

Do you wish to login to the Admin UI as "openvpn"?
> Press ENTER for default [yes]: 
> Specify the username for an existing user or for the new user account: Note: This user already exists.

> Please specify your Activation key (or leave blank to specify later): 


Initializing OpenVPN...
Removing Cluster Admin user login...
userdel "admin_c"
Adding new user login...
useradd -s /sbin/nologin "admin"
Writing as configuration file...
Perform sa init...
Wiping any previous userdb...
Creating default profile...
Modifying default profile...
Adding new user to userdb...
Modifying new user as superuser in userdb...
Getting hostname...
Hostname: 157b39c3fd6a
Preparing web certificates...
Getting web user account...
Adding web group account...
Adding web group...
Adjusting license directory ownership...
Initializing confdb...
Generating PAM config...
Enabling service
Error: Could not execute 'systemctl enable openvpnas' to enable startup/shutdown scripts
Stopping openvpn-as now; will start again later after configuring
cat: /var/run/openvpnas.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
[cont-init.d] 40-openvpn-init: exited 0.
[cont-init.d] 50-interface: executing... 
MOD Default {'admin_ui.https.ip_address': None} {'admin_ui.https.ip_address': 'eth0'}
MOD Default {'cs.https.ip_address': None} {'cs.https.ip_address': 'eth0'}
MOD Default {'vpn.daemon.0.listen.ip_address': None} {'vpn.daemon.0.listen.ip_address': 'eth0'}
MOD Default {'vpn.daemon.0.server.ip_address': None} {'vpn.daemon.0.server.ip_address': 'eth0'}
[cont-init.d] 50-interface: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.`

**Comment by aptalca** [comment]
That's irrelevant.

Are you using https? Post what address you're trying to browse

**Comment by capriciousduck** [comment]
No. I'm not using https. I am using http.

**Comment by aptalca** [comment]
https://media.giphy.com/media/MPLpvJcsWvrkk/giphy.gif

**Comment by capriciousduck** [comment]
What's that?

**Comment by tobbenb** [comment]
A giphy. Just click the link and you will see it.

**Comment by capriciousduck** [comment]
It says "Well there it is" what does that do with this app?

You mean I should use https? I already tried with https. Still same result.

**Comment by tobbenb** [comment]
Admin interface is https only.
What is the full address you use for the admin interface?

**Comment by capriciousduck** [comment]
I am using this URL to access my openvpn server.

[https://45.148.29.149:943/admin](url)

**Comment by capriciousduck** [comment]
It's working now. Maybe it's my browser issue.

**Comment by capriciousduck** [comment]
I am getting some session errors. Any previous stable images?

**Comment by capriciousduck** [comment]
Any other alternative which provides a web UI interface like openvpn?
