### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by bandwiches** [linuxserver/docker-openvpn-as#131]
Your docs are a little misleading.  README states that you support `arm64`, `armhf`, and `x86-64` but OpenVPN doesn't even support `arm`.

**Comment by Roxedus** [comment]
Read the full text.
https://github.com/linuxserver/docker-openvpn-as#supported-architectures

**The architectures supported by this image are:**

**Comment by bandwiches** [comment]
Thanks for closing my ticket and passing me off as some idiot but I think it's imperative that you document your project correctly.

Here's a screenshot of your readme.

![Screenshot_20201014-062633](https://user-images.githubusercontent.com/16140382/95982927-6d296280-0de6-11eb-8e99-f6d96bba2ba7.png)

Your repo on docker hub has a grand total of 0 ARM based images.  In fact, there is not even 1 historical release tagged for ARM.

Your docs state that you support ARM.

You do not support ARM.

This is important for others who stumble upon your github repo to know that you do not support ARM and you won't until openvpn-as supports ARM.

Your documentation is misleading at best.

**Comment by Roxedus** [comment]
That part of the docs is the same for all of our images, the highlighted text does not say that *this* image supports arm. Only the text for the table does.

**Comment by bandwiches** [comment]
This is a much better explanation, I see it now. Assuming users are going to search through all of your projects to form the understanding that this is a blanket statement is a pretty big stretch.  To each their own though.  Thanks!

**Comment by Roxedus** [comment]
Its a pretty big blanket :) I estimate 98% of our images supports all those arches

**Comment by bandwiches** [comment]
Totally understand, but not every user is looking to use all your projects and images or even has the need to look at them.  I think it can be argued both ways, but all-in-all it would be much simpler if openvpn-as would move to ARM!
