### ISSUE TITLE
Request: arm64/armhf version

### ISSUE THREAD

**Issue by klara31** [linuxserver/docker-openvpn-as#136]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Currently only an amd64 version is available

## Current Behavior
Please provide an armor/arm64 version as well, so this container can run on a Raspberry Pi.

## Steps to Reproduce

N.A.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by j0nnymoe** [comment]
Won't happen as openvpn don't provide binaries for these platforms.
