### ISSUE TITLE
Add support for multiple architectures, specifically arm64 and armhf, to the released docker image.

### ISSUE THREAD

**Issue by f-steff** [linuxserver/docker-openvpn-as#142]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Operate out of the box on arm64 and armhf

## Current Behavior
Wrong architecture

## Alternatives Considered
Checked if other docker images exist that supports arm64 and armhf. Only old images, based on linuxservers work, exist for armhf.

**Comment by tobbenb** [comment]
There are no arm binaries available for openvpn-as. You would have to ask openvpn to compile them.
