### ISSUE TITLE
Cant access webui

### ISSUE THREAD

**Issue by cawk** [linuxserver/docker-openvpn-as#45]
i installed this into my unraid 6.6.6 used the bond0 interface as thats what was listed in the information tab
then once i try to access webui i just get hit with refused to connect

**Comment by aptalca** [comment]
logs?

**Comment by cawk** [comment]
i have managed to get it working to access the webui i then continued with the setup and then downloaded my profiles i then get an issue saying could not establish a connection with vpn 

my ports are open and there is no firewall running on the router

**Comment by thelamer** [comment]
Again we need information to help you. 

I am closing this issue, please detail a specific issue you are facing in a new one. 

Please include your docker run command or compose and any logs you get from the container for the error.
