### ISSUE TITLE
Language of the Webui openVPN

### ISSUE THREAD

**Issue by mario26** [linuxserver/docker-openvpn-as#64]
Hi!

I just installed your docker, it works great! 

I was wondering if it is possible to change the language of the openVPN web interface?

If so, can you tell me how to do it?

Thank you.

**Comment by j0nnymoe** [comment]
If it's possible, it'll be documented in the openvpn-as documentation: https://openvpn.net/vpn-server-resources/ .

Hope this helps.

**Comment by mario26** [comment]
@j0nnymoe, i add this to my environment:

```
        environment:
                ...
                - TZ=Europe/Paris
                - LANG=fr_FR.UTF-8
                - LANGUAGE=fr_FR.UTF-8
                ...
```
It does not work translation.

I spent some time in the openVPN documentation, either i do not really look for it, or no information about it, do you have experience feedback?

Thank you for your quick reply !
