### ISSUE TITLE
Add/Remove user with bash shell

### ISSUE THREAD

**Issue by mario26** [linuxserver/docker-openvpn-as#65]
Hi !

Is it possible to add/remove users with a bash shell without going through the Webui using "docker exec" for example?

If so, can you show me some examples?

Thank you

**Comment by aptalca** [comment]
This isn't really an issue with the docker container, but you can start here: https://openvpn.net/vpn-server-resources/managing-user-and-group-properties-from-command-line/

**Comment by mario26** [comment]
Ok thank you, it will be very useful!
