### ISSUE TITLE
openVPN with Nginx and Letsencrypt

### ISSUE THREAD

**Issue by mario26** [linuxserver/docker-openvpn-as#68]
Hi!

Following my last issue, here: https://github.com/linuxserver/docker-openvpn-as/issues/67, i realized that I had a problem with SSL, my Internet browser no longer allows me to add an "exception".

I thinked openVPN was not executed any more, please excuse me...

I have a friend have connected with another Internet connection by adding an "exeption". So, i restarted all my computers and routeurs, emptied the cache of my browsers and i still have not the possibility to add an "exception".

```
HTTP Strict Transport Security (HSTS)
Code d’erreur : SEC_ERROR_UNKNOWN_ISSUER
```

So, i tryed from a tablet in Android, i have the same problem in Firefox, i have not the possibility to add an "exception",  but in Chrome openVPN is displayed, I could added an exception!

I remember now having tried to pass the webui in the proxy of Nginx, it seems to me that it was at that moment that it did not work at my home anymore...

I wanted to avoid showing ugly port in the url:
```
server {
        listen 80;
        server_name vpn.domaine.org;

        include /var/www/snippets/letsencrypt.conf;
        include /var/www/snippets/geoip.conf;

        return 301 https://$host$request_uri;

        error_log /var/log/nginx/local_error.log;
        access_log /var/log/nginx/local_access.log;

    location / {
        proxy_pass http://172.16.0.130:943; #Adress IP containerr
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_read_timeout 90;
    }
}

server {
        listen 443 ssl http2;
        server_name vpn.domaine.org;

        include /var/www/snippets/ssl.conf;
        include /var/www/snippets/letsencrypt.conf;
        include /var/www/snippets/geoip.conf;

        error_log /var/log/nginx/local_error.log;
        access_log /var/log/nginx/local_access.log;

    location / {
        proxy_pass 172.16.0.130:943 ; #Adress IP container
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_read_timeout 90;
    }
}
```

The Letsencrypt wildcard certificate is called in the Nginx configuration file, can we somehow concatenate the certificates present in /etc/web-ssl/ of your Docker image?

Exemple:
```
cat /etc/letsencrypt/live/devosi.org/fullchain.pem >> /my-docker/config/openvpn/etc/web-ssl/ca.crt
cat /etc/letsencrypt/live/domaine.org/privkey.pem >> /my-docker/config/openvpn/etc/web-ssl/ca.key
cat /etc/letsencrypt/live/domaine.org/cert.pem >> /my-docker/config/openvpn/etc/web-ssl/server.crt
cat /etc/letsencrypt/live/domaine.org/privkey.pem >> /my-docker/config/openvpn/etc/web-ssl/server.key
```

I do not quite understand what happened, the server openVPN works, a friend has access to my OpenVPN Webui from another computer from another Internet connection but does not work my home...

I would like to pass the openVPN Webui via a proxy to avoid displaying an ugly port and having a validated certificate, but i must not do it properly...

I have other Nginx proxys with other containers, i have no problem, it works...

Can you help me ?

**Comment by thelamer** [comment]
I Dare you to open another issue. I already told you this is not a support forum. 

This is Github, you are wasting many developers time every time every time you do this.

**Comment by mario26** [comment]
@thelamer i'm sorry for you wasting time, i do not know any forum that deals with Docker and your image except here.

I want to make your image work because it seems to me correct, i need a powerful VPN and well parameterized with Docker.

If i succeed, i will not fail to thank you, i need some help, so if anyone can point me to a solution?

I do not want to go into a challenge of the one who opens the most Issue, my goal, not to disturb you, but find how to properly configure your image on my server...

I thank you for the time you took with me!

**Comment by thelamer** [comment]
https://discord.gg/YWrKVTn
