### ISSUE TITLE
Permission denied for scripts in /usr/local/openvpn_as

### ISSUE THREAD

**Issue by godfuture** [linuxserver/docker-openvpn-as#90]
Permission denied for scripts in /usr/local/openvpn_as. Admin page is not available. No matter the permission of the config folder or env parameter to the container, scripts fail.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Debian 9

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-time: executing...

Current default time zone: 'Europe/Berlin'
Local time is now:      Thu Sep 26 02:38:03 CEST 2019.
Universal Time is now:  Thu Sep 26 00:38:03 UTC 2019.

[cont-init.d] 20-time: exited 0.
[cont-init.d] 30-config: executing...
installing openvpn-as for the first time
Selecting previously unselected package openvpn-as-bundled-clients.
(Reading database ... 11518 files and directories currently installed.)
Preparing to unpack /openvpn/openvpn-clients.deb ...
Unpacking openvpn-as-bundled-clients (2) ...
Setting up openvpn-as-bundled-clients (2) ...
Selecting previously unselected package openvpn-as.
(Reading database ... 11531 files and directories currently installed.)
Preparing to unpack /openvpn/openvpn.deb ...
Unpacking openvpn-as (2.7.5-932a08a3-Ubuntu18) ...
Setting up openvpn-as (2.7.5-932a08a3-Ubuntu18) ...
Automatic configuration failed, see /usr/local/openvpn_as/init.log
You can configure manually using the /usr/local/openvpn_as/bin/ovpn-init tool.
/var/lib/dpkg/info/openvpn-as.postinst: line 200: /usr/local/openvpn_as/scripts/confdba: Permission denied
Beginning with OpenVPN AS 2.6.0 compression is disabled by default and on upgrades as security patch.
/var/lib/dpkg/info/openvpn-as.postinst: line 204: /usr/local/openvpn_as/scripts/confdba: Permission denied
Stopping openvpn-as now; will start again later after configuring
cat: /var/run/openvpnas.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-openvpn-init: executing...
/var/run/s6/etc/cont-init.d/40-openvpn-init: line 14: /usr/local/openvpn_as/bin/ovpn-init: Permission denied
Stopping openvpn-as now; will start again later after configuring
cat: /var/run/openvpnas.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
[cont-init.d] 40-openvpn-init: exited 0.
[cont-init.d] 50-interface: executing...
/var/run/s6/etc/cont-init.d/50-interface: line 9: /usr/local/openvpn_as/scripts/confdba: Permission denied
/var/run/s6/etc/cont-init.d/50-interface: line 10: /usr/local/openvpn_as/scripts/confdba: Permission denied
/var/run/s6/etc/cont-init.d/50-interface: line 11: /usr/local/openvpn_as/scripts/confdba: Permission denied
/var/run/s6/etc/cont-init.d/50-interface: line 12: /usr/local/openvpn_as/scripts/confdba: Permission denied
[cont-init.d] 50-interface: exited 126.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
./run: line 3: /usr/local/openvpn_as/scripts/openvpnas: Permission denied
[services.d] done.
./run: line 3: /usr/local/openvpn_as/scripts/openvpnas: Permission denied
```

No.

##  Thanks, team linuxserver.io

**Comment by aptalca** [comment]
Please post:
1) The command you used to create the container
2) How you installed docker

**Comment by godfuture** [comment]
I am using OMV 4 and its gui plugin. I filled all fields mentioned in the readme.

**Comment by aptalca** [comment]
We need to know what you put into those fields otherwise we can't help

**Comment by godfuture** [comment]
Here is the complete container info: [https://pastebin.com/LYxxj4JV](https://pastebin.com/LYxxj4JV)

Hope this helps. Thanks a lot!

**Comment by ParadingLunatic** [comment]
I have the exact same issue.  I currently have it running on a physical OMV4 server and I'm trying to move everything to a virtual OMV install.  I copied my config folder to the new server and made sure to chown the folder to give it proper rights and got that error.  I figured I'll try to start from scratch and deleted the files in the config folder entirely and restarted the container and got the same error.  Deleted the container, image, config folder and repulled the image, recreated the container, etc, still the same error.  I'm not sure why it's working in one place, but not the other.

**Comment by ParadingLunatic** [comment]
I think I might know what the issue is.  I haven't tested it out yet, but it makes sense.  I remember coming across this issue ages ago when I first set this up.  See here.  
[https://forum.openmediavault.org/index.php/Thread/25750-OpenVPN-AS-Docker-Container-Fails-to-Start-with-Script-Permission-Denied-Errors/](url)

**Comment by aptalca** [comment]
Yes, if the drive that holds the config folder is set to noexec, that would do it. Make sure the files in the config folder are executable

**Comment by ParadingLunatic** [comment]
Bingo, that was the issue.  OMV by default mounts file systems that store data (used for shared folders) with noexec enabled.  Once you change noexec to exec, save, and rebuild fstab using omv-mkconf fstab, then reboot, it works.

**Comment by aptalca** [comment]
That would lead to a number of issues with various containers. There should be a general warning in OMV docs or their forum

**Comment by godfuture** [comment]
Thanks for helping here! I guess the default docker home is not located on shared folder. I will inform community in OMV forum.

**Comment by godfuture** [comment]
Issue was solved by changing the mount option from noexec to exec. Thanks all!
