### ISSUE TITLE
Listen to one IP-Address

### ISSUE THREAD

**Issue by Happyfeet01** [linuxserver/docker-openvpn-as#92]
Hello,

I set it up today and it works. But how can I make it possible that OpenVPN listen only to one IP-Address?  I have two IP‘s on one Networkinterface.( enp4s0)

>

------------------------------

## Expected Behavior
Deactivate one IP Address on the same Network Adapter. Ob this way i change the tcp Port from 9443 to 443 to hide the VPN Network. 
At the other address I have multiple Website on port 443. 

## Current Behavior
can only turn both IP Adresses on. Listen to only one Address is not possible.

## Steps to Reproduce

1. add an second IP to the Server
2. sudo ip address add <new ip> dev enp4s0
3. Login to the Admin Panel, try to switch off one Address

## Environment
**OS:**   
Ubuntu 18.04.3 LTS
   
**CPU architecture:** x86_64/arm32/arm64  
x86_64    
**How docker service was installed:**      

## Command used to create docker container (run/create/compose/screenshot)

sudo docker create --name=openvpn-as \
--restart=always \
-v /home/docker/openvpn-as/config:/config \
-e INTERFACE=enp4s0 \
-e PGID=1001 -e PUID=1001 \
-e TZ=Europe/Berlin \
--net=host --privileged \
linuxserver/openvpn-as

## Docker logs

`Please enter 'yes' to indicate your agreement [no]: 
Once you provide a few initial configuration settings,
OpenVPN Access Server can be configured by accessing
its Admin Web UI using your Web browser.

Will this be the primary Access Server node?
(enter 'no' to configure as a backup or standby node)
> Press ENTER for default [yes]: 
Please specify the network interface and IP address to be
used by the Admin Web UI:
(1) all interfaces: 0.0.0.0
(2) enp4s0: 188.40.63.58
(3) br-f84bcbd73320: 172.18.0.1
(4) br-2faff5558deb: 192.168.208.1
(5) br-4acdf0e18be1: 172.19.0.1
(6) docker0: 172.17.0.1
(7) br-7f11e03648bb: 172.24.0.1
(8) br-9b5f3d5bd4a3: 172.21.0.1
(9) br-d2c6169b838e: 192.168.0.1
(10) br-1a76fc027f79: 172.25.0.1
(11) br-mailcow: 172.22.1.1
Please enter the option number from the list above (1-11).
> Press Enter for default [1]: 
Please specify the port number for the Admin Web UI.
> Press ENTER for default [943]: 
Please specify the TCP port number for the OpenVPN Daemon
> Press ENTER for default [1194]: 
Should client traffic be routed by default through the VPN?
> Press ENTER for default [yes]: 
Should client DNS traffic be routed by default through the VPN?
> Press ENTER for default [yes]: 
Use local authentication via internal DB?
> Press ENTER for default [yes]: 
Private subnets detected: ['172.17.0.0/16']

Should private subnets be accessible to clients by default?
> Press ENTER for default [yes]: 
To initially login to the Admin Web UI, you must use a
username and password that successfully authenticates you
with the host UNIX system (you can later modify the settings
so that RADIUS or LDAP is used for authentication instead).

You can login to the Admin Web UI as "openvpn" or specify
a different user account to use for this purpose.

Do you wish to login to the Admin UI as "openvpn"?
> Press ENTER for default [yes]: 
> Specify the username for an existing user or for the new user account: Note: This user already exists.

> Please specify your OpenVPN-AS license key (or leave blank to specify later): 

Initializing OpenVPN...
Removing Cluster Admin user login...
userdel "admin_c"
Adding new user login...
useradd -s /sbin/nologin "admin"
Writing as configuration file...
Perform sa init...
Wiping any previous userdb...
Creating default profile...
Modifying default profile...
Adding new user to userdb...
Modifying new user as superuser in userdb...
Getting hostname...
Hostname: larsmueller.net
Preparing web certificates...
Getting web user account...
Adding web group account...
Adding web group...
Adjusting license directory ownership...
Initializing confdb...
Generating init scripts...
Generating PAM config...
Generating init scripts auto command...
Starting openvpnas...

NOTE: Your system clock must be correct for OpenVPN Access Server
to perform correctly.  Please ensure that your time and date
are correct on this system.

Initial Configuration Complete!

You can now continue configuring OpenVPN Access Server by
directing your Web browser to this URL:

https://188.40.63.58:943/admin
Login as "admin" with the same password used to authenticate
to this UNIX host.

During normal operation, OpenVPN AS can be accessed via these URLs:
Admin  UI: https://188.40.63.58:943/admin
Client UI: https://188.40.63.58:943/

See the Release Notes for this release at:
   https://openvpn.net/vpn-server-resources/release-notes/

Stopping openvpn-as now; will start again later after configuring
[cont-init.d] 40-openvpn-init: exited 0.
[cont-init.d] 50-interface: executing... 
MOD Default {'admin_ui.https.ip_address': None} {'admin_ui.https.ip_address': 'enp4s0'}
MOD Default {'cs.https.ip_address': None} {'cs.https.ip_address': 'enp4s0'}
MOD Default {'vpn.daemon.0.listen.ip_address': None} {'vpn.daemon.0.listen.ip_address': 'enp4s0'}
MOD Default {'vpn.daemon.0.server.ip_address': None} {'vpn.daemon.0.server.ip_address': 'enp4s0'}
[cont-init.d] 50-interface: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done. `

**Comment by Happyfeet01** [comment]
I mean this https://cloud.larsmueller.net/s/p6Kme75SDDPYxoS

**Comment by j0nnymoe** [comment]
This still isn't enough information. Our issue template asks for some specific information. Please provide this info first.

**Comment by Happyfeet01** [comment]
Infos are updated, sorry for that.

**Comment by aptalca** [comment]
Try switching off "listen on all interfaces" and then you should be able to turn on/off the others

**Comment by Happyfeet01** [comment]
Not working, I can only switch both on. Maybe I reboot the server with the new Adress and try it again

**Comment by aptalca** [comment]
If it's not possible in the app gui, it is not possible to do so with this image. We only tell the app which interface to use. The app figures out the IPs associated.

You should contact them on their forums
